export const GET_CART = "GET_CART";
export const UPDATE_CART_ITEM_QUANTITY  = "UPDATE_CART_ITEM_QUANTITY";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const ADD_CART_ITEM = "ADD_CART_ITEM";